name: Semgrep
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  semgrep:
    name: Semgrep
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config-file: ".semgrep.yml"
