name: Semgrep Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      # Checkout project source
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Semgrep
      - name: Install Semgrep
        run: sudo apt-get install semgrep

      # Run Semgrep using default rules
      - name: Run Semgrep
        run: semgrep

